Repository hmcts/cnp-plum-shared-infrastructure, pull requests merged in 2024-02, with the labels that each got.

#121 DTSPO-14238 - daily cap and alerting
  aat.tfvars
  application-insights.tf
  ithc.tfvars
  main.tf
  prod.tfvars
  sandbox.tfvars
  servicebus.tf
  variables.tf
  vault.tf
Labels: add-or-update

#122 setting loca vars for sandbox
  application-insights.tf
Labels: no-changes

#123 adding short name action group
  application-insights.tf
Labels: add-or-update

#125 DTSPO-14998 fix error on pipeline
  application-insights.tf
Labels: destroy

#127 DTSPO-14997 - testing single action group and function app
  application-insights.tf
Labels: destroy

#128 Switch back to main branch after merging App insight brnach.
  application-insights.tf
Labels: no-changes
